### ISSUE TITLE
IE8 ondersteunt geen viewport units

### ISSUE THREAD

**Issue by krijnhoetmer** [LeanderVanBaekel/LeanderVanBaekel.github.io#15]
Interessant, een aparte stylesheet voor IE, omdat die media queries niet ondersteunt.. :) Maar ondersteunt die wel de `vw` unit dan? Volgens mij kun je dit eleganter oplossen, zonder een extra stylesheet te maken (want die gaat vergeten worden zodra je wat styles in je main stylesheet verandert).

**Comment by krijnhoetmer** [comment]
Kijk ook naar `</header class='header'>`, die je in de IE stylesheet probeert te selecteren met `.header h1`. Volgens mij doet dit ook niet wat je wilt dat het doet.

**Comment by LeanderVanBaekel** [comment]
Ik heb de extra stylesheet weggehaald en de layout aangepast zodat hij met minder css constanter blijft in oudere browsers. 

https://github.com/LeanderVanBaekel/LeanderVanBaekel.github.io/blob/master/browserTechnologies/her/site/style2.css

**Comment by KoopReynders** [comment]
done
