### ISSUE TITLE
Demo breekt volledig in IE8

### ISSUE THREAD

**Issue by krijnhoetmer** [LeanderVanBaekel/LeanderVanBaekel.github.io#16]
Los van de layout krijg ik JS errors; wat wil je dat daar gebeurt?

**Comment by LeanderVanBaekel** [comment]
Ik heb meer Feature detections in de JS verwerkt waardoor in oudere IE versies er geen errors meer onstaan.

https://github.com/LeanderVanBaekel/LeanderVanBaekel.github.io/blob/master/browserTechnologies/her/site/script.js

**Comment by KoopReynders** [comment]
done
