### ISSUE TITLE
Aantal feature detects ontbreken

### ISSUE THREAD

**Issue by krijnhoetmer** [LeanderVanBaekel/LeanderVanBaekel.github.io#17]
Je gebruikt een aantal browser APIs waarvan je niet test of ze wel beschikbaar zijn (gerelateerd aan #16).

**Comment by LeanderVanBaekel** [comment]
Ik heb meer Feature detections in de JS verwerkt waardoor in oudere IE versies er geen errors meer onstaan.

https://github.com/LeanderVanBaekel/LeanderVanBaekel.github.io/blob/master/browserTechnologies/her/site/script.js

**Comment by KoopReynders** [comment]
done
