### ISSUE TITLE
Te weinig fallback voor CSS features

### ISSUE THREAD

**Issue by krijnhoetmer** [LeanderVanBaekel/LeanderVanBaekel.github.io#18]
Relatief nieuwe features als `rem`, `calc()`, `rgba()` en `vw`; bouw hiervoor wel de juiste fallbacks in. Probeer ook specifiek te testen in browsers die deze onderdelen niet ondersteunen, om te kijken wat er stuk gaat, en hoe je dat kunt voorkomen.

**Comment by LeanderVanBaekel** [comment]
Ik heb de css opnieuw geschreven dmv PE.

https://github.com/LeanderVanBaekel/LeanderVanBaekel.github.io/blob/master/browserTechnologies/her/site/style2.css

**Comment by KoopReynders** [comment]
done
