### ISSUE TITLE
Button click doet meerdere dingen

### ISSUE THREAD

**Issue by krijnhoetmer** [LeanderVanBaekel/LeanderVanBaekel.github.io#19]
Je doet iets in JavaScript, maar laat ook het `form` submitten. Wat wil je dat hier gebeurt, en/of klopt dit gedrag volledig? Die toegevoegde `form` tag daar klopt ergens wel, maar volgens mij moet je nog wat stappen uitvoeren om het goed werkend te krijgen.

**Comment by LeanderVanBaekel** [comment]
Zodra de button events via javascript worden ondersteund wordt er nu een preventDefault functie uitgevoerd op het formulier zodat er geen dubbele actie ontstaat.

**Comment by LeanderVanBaekel** [comment]
https://github.com/LeanderVanBaekel/LeanderVanBaekel.github.io/blob/master/browserTechnologies/her/site/script.js

**Comment by KoopReynders** [comment]
done
